<div class="container">

<h1 class="h1"><?php echo $this->getTitle();?></h1>
    <form action="/posts/store" method="post" accept-charset="utf-8">

        <div class="form-group">
            <label for="title">Titulo</label>
            <input  title="title" type="text" name="title" class ="form-control">
        </div>

        <div class="form-group">
            <label for="content">content</label>
            <textarea name="content" class="form-control" rows="15"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="/posts" class="btn btn-default">Cancelar</a>
    
    </form>
</div>