<div class="container">
    <div class="row">
        <h1 class="h1">
            <?php echo $this->getTitle(); ?>
            <a href="/posts/create" class="btn btn-primary pull-right">
                <i class=""glyphicon glyphicon-plus-sign></i>Novo post
            </a>
        </h1>
    </div>

    <?php foreach($this->view->posts as $post): ?>
        <div class="row">
            <a href="/posts/<?php echo $post->id;?>/show"><h3 class="h3"><?php echo $post->title; ?></h3></a>
            <p class="text-justify"><?php echo $post->content; ?></p>
        </div>
        <p class="text-right">
            <a href="/posts/<?php echo $post->id; ?>/edit" class="btn btn-warning btn-xs">
                <i class="glyphicon glyphicon-pencil"></i>
            </a>
             <a href="/posts/<?php echo $post->id; ?>/delete" class="btn btn-danger btn-xs" onclick="return confirm('Deseja deletar este post?')">
                <i class="glyphicon glyphicon-remove-sign"></i>
            </a>
        </p>

        <hr>
    <?php endforeach; ?>

</div>