<div class="container">
    <div class="row">
        <h2 class="h2 col-xs-12"><?php $this->getTitle(); ?></h2>
    </div>
    <div class="row">
       
    </div>
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
            <h1 class="h1 text-center">Jeyziel Micro Framework</h1>
            <p>
                Este é um micro framework MVC em PHP, construído para colocar em prática meus conhecimentos com a linguagem php e a arquitetura mvc.
            </p>
            <p><?php echo $this->view->posts[0]->title ?></p>
           
        </div>
    </div>
</div>